DROP TABLE PARTICIPANTE;

CREATE TABLE PARTICIPANTE (
    ID_ASOCIADO NUMBER(8),
    NOMBRE NVARCHAR2(50) NOT NULL,
    APELLIDO_P NVARCHAR2(50) NOT NULL,
    APELLIDO_M NVARCHAR2(50) NOT NULL,
    CONSTRAINT PARTICIPANTE_PK PRIMARY KEY(ID_ASOCIADO),
    CHECK (ID_ASOCIADO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
);

CREATE TABLE 